#!/usr/bin/env python3
"""Turn verified "command comes from package" claims into src/symbols.inc.

    tools/mine-cs.sh > cs-index.tsv
    tools/verify-hints.sh tools/symbols.tsv cs-index.tsv > verify.out
    tools/gen-symbols.py --curated tools/symbols.tsv --mined cs-index.tsv \\
                         --verified verify.out > src/symbols.inc

The output is committed. Building pplatex must never need TeX Live, python or
a network: the release builds are static binaries for three platforms and the
whole point of generating this ahead of time is that they stay that way.

Only claims that survived verification are written out. A claim the checker
rejected is dropped rather than marked doubtful, because the checker rejects
claims that are false, and there is no useful way to phrase advice that is
false. Anything it could not check is dropped too -- the table is the thing
the tool speaks with confidence from, so everything in it has been confirmed
against a real distribution.
"""

import argparse
import re
import sys


def read_claims(path):
    """Read a "<command>\\t<package>" file, ignoring comments and blanks."""
    claims = {}
    with open(path, encoding='utf-8') as handle:
        for line in handle:
            line = line.rstrip('\n')
            if not line.strip() or line.lstrip().startswith('#'):
                continue
            parts = line.split('\t')
            if len(parts) != 2 or not parts[0].startswith('\\'):
                print(f'{path}: ignoring malformed line: {line!r}', file=sys.stderr)
                continue
            command, package = parts[0].strip(), parts[1].strip()
            if command and package:
                claims[command] = package
    return claims


def read_rejects(path):
    """Pull "\\command -> package" pairs out of verify-hints.sh output."""
    rejects = set()
    pattern = re.compile(r'^FAIL \\(\S+) -> (\S+):')
    with open(path, encoding='utf-8') as handle:
        for line in handle:
            found = pattern.match(line)
            if found:
                rejects.add(('\\' + found.group(1), found.group(2)))
    return rejects


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--curated', required=True,
                        help='hand written claims; these win')
    parser.add_argument('--mined', required=True,
                        help='claims scraped by tools/mine-cs.sh')
    parser.add_argument('--verified', required=True,
                        help='output of tools/verify-hints.sh')
    parser.add_argument('--kernel', required=True,
                        help='kernel commands, from tools/mine-cs.sh --kernel')
    parser.add_argument('--source', default='TeX Live',
                        help='distribution the claims were checked against')
    args = parser.parse_args()

    # Mined first, then curated on top: a hand written claim is there precisely
    # because the scrape got it wrong or could not see it.
    claims = read_claims(args.mined)
    claims.update(read_claims(args.curated))

    rejects = read_rejects(args.verified)
    kept = {c: p for c, p in claims.items() if (c, p) not in rejects}

    dropped = len(claims) - len(kept)
    print(f'{len(claims)} claims, {dropped} rejected, {len(kept)} kept',
          file=sys.stderr)

    if not kept:
        print('nothing survived verification; refusing to write an empty table',
              file=sys.stderr)
        return 1

    packages = sorted({p for p in kept.values()})
    if len(packages) > 255:
        print(f'{len(packages)} packages will not fit in a byte index',
              file=sys.stderr)
        return 1
    index = {name: i for i, name in enumerate(packages)}

    out = sys.stdout
    out.write('/* Generated by tools/gen-symbols.py -- do not edit.\n')
    out.write(' *\n')
    out.write(f' * Which package defines a command, checked against {args.source}:\n')
    out.write(' * every entry was confirmed by compiling a document that loads the\n')
    out.write(' * package and one that does not, so a command the kernel already\n')
    out.write(' * provides cannot appear here. Regenerate with:\n')
    out.write(' *\n')
    out.write(' *   tools/mine-cs.sh > cs-index.tsv\n')
    out.write(' *   tools/verify-hints.sh tools/symbols.tsv cs-index.tsv > verify.out\n')
    out.write(' *   tools/gen-symbols.py --curated tools/symbols.tsv \\\n')
    out.write(' *       --mined cs-index.tsv --verified verify.out > src/symbols.inc\n')
    out.write(' */\n\n')

    out.write('static const char *const SYMBOL_PACKAGES[] = {\n')
    for name in packages:
        out.write(f'    "{name}",\n')
    out.write('};\n\n')

    out.write('static const struct {\n')
    out.write('    const char *command;\n')
    out.write('    unsigned char package;\n')
    out.write('} SYMBOLS[] = {\n')
    # Sorted so the lookup can binary search.
    for command in sorted(kept):
        escaped = command.replace('\\', '\\\\')
        out.write(f'    {{ "{escaped}", {index[kept[command]]} }},'
                  f'  /* {kept[command]} */\n')
    out.write('};\n\n')

    # The kernel names carry no package, and exist only so that a spelling
    # suggestion can reach them. Without these, \superseteq gets no answer,
    # because the command it is a typo for is in the kernel and so is
    # deliberately absent from the table above.
    with open(args.kernel, encoding='utf-8') as handle:
        kernel = sorted({line.strip() for line in handle
                         if line.strip().startswith('\\')})

    out.write('/* Commands the kernel provides. No package fixes these; they\n')
    out.write(' * are here only so a misspelling can be matched against them. */\n')
    out.write('static const char *const KERNEL_COMMANDS[] = {\n')
    for command in kernel:
        out.write(f'    "{command.replace(chr(92), chr(92)*2)}",\n')
    out.write('};\n')

    print(f'{len(kernel)} kernel commands', file=sys.stderr)

    return 0


if __name__ == '__main__':
    sys.exit(main())
