/***********************************************************************************
    begin                : Die Sep 16 2003
    copyright            : (C) 2003 by Jeroen Wijnhout (wijnhout@science.uva.nl)
			       2009 by Stefan Hepp (stefan@stefant.org)

    This file is taken from the Kile project and modified to work without Qt on
    the cmdline by Stefan Hepp (stefan@stefant.org).
 ***********************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

#ifndef LATEXOUTPUTFILTER_H
#define LATEXOUTPUTFILTER_H

#include "outputinfo.h"

#include <cstdio>
#include <string>
#include <stack>

/**
 * An object of this class is used to parse the output messages
 * generated by a TeX/LaTeX-compiler.

 * @author Thorsten Lck
 * @author Jeroen Wijnhout
 * @author Stefan Hepp
 */

class LOFStackItem
{
public:
	explicit LOFStackItem(const std::string& file = "", bool sure = false) : m_file(file), m_reliable(sure) {}

	const std::string & file() const { return m_file; }
	void setFile(const std::string & file) { m_file = file; }

	bool reliable() const { return m_reliable; }
	void setReliable(bool sure) { m_reliable = sure; }

private:
	std::string m_file;
	bool m_reliable;
};

class LatexOutputFilter
{
    public:
        LatexOutputFilter(const std::string& source, int verbose, bool nobadboxes, bool quiet);
        ~LatexOutputFilter();

        /** Read the compiler output and print every message found in it. */
        bool run(FILE *out);

	/**
	Dump the structured item rather than rendering it. Undocumented option,
	used to pin down what the parser understood without waiting for a
	renderer to show it.
	*/
	void setDebugModel(bool debug) { m_debugModel = debug; }

	enum {Start = 0, FileName, FileNameHeuristic, Error, Warning, BadBox, LineNumber};

    protected:
        /**
        Parses the given line for the start of new files or the end of
        old files.
        */
        void updateFileStack(const std::string &strLine, short & dwCookie);
	void updateFileStackHeuristic(const std::string &strLine, short & dwCookie);

        /**
        Forwards the currently parsed item to the item list.
        */
        void flushCurrentItem();

	/**
	Hand a finished item to the output, one item behind.

	TeX prints an error before the context that explains it, and in
	file:line:error style the context arrives after the item has already
	been completed. Holding the most recent item back by one lets that
	context still be attached to the item it belongs to. Depth one is
	enough: TeX never interleaves the contexts of two errors.
	*/
	void emitItem(const LatexOutputInfo& item, bool visible);

	/** Print the held-back item, if any, and empty the slot. */
	void releasePending();

	/**
	Watch the raw line for one half of a TeX error context and pair it with
	the half before it.

	Runs ahead of the detectors and never consumes anything: it only reads
	m_rawLine and fills in fields nothing else touches, so the messages the
	detectors build are unaffected either way.
	*/
	void observeContext();

	/** Hand a completed context to whichever item it belongs to. */
	void storeContext(TexContext& context);

	/**
	The item a context should attach to: the one being parsed, or else the
	one just completed. An "l.<n>" line is what tells the parser an error
	is over, so by the time its other half arrives the item has already
	been finished and handed to the pending slot.
	*/
	LatexOutputInfo* contextTarget();

        // overridings
    public:
        /** Return number of errors etc. found in log-file. */
	void getErrorCount(int *errors, int *warnings, int *badboxes);
	void clearErrorCount() { m_nErrors=m_nWarnings=m_nBadBoxes=0 ; }

    protected:
	short parseLine(const std::string & strLine, short dwCookie);

	const std::string& source() const { return m_source; }
	const std::string& path() const { return m_srcPath; }

	/** Zero based index of the currently parsed line in the output file. */
	int GetCurrentOutputLine() const { return m_nOutputLines; }

	bool detectError(const std::string & strLine, short &dwCookie);
	bool detectFileLineError(const std::string & strLine, short &dwCookie);
	bool detectWarning(const std::string & strLine, short &dwCookie);
	bool detectBadBox(const std::string & strLine, short &dwCookie);
	bool detectLaTeXLineNumber(std::string & warning, short & dwCookie, size_t len);
	bool detectBadBoxLineNumber(std::string & strLine, short & dwCookie, size_t len);

	bool fileExists(const std::string & name);

	/**
	Source file named by a file:line:error message. Overrides the file stack
	for the current item only, since that format states the file outright.
	*/
	std::string m_fileLineSource;

	/** 
	Check if we need to add a space when we append a message to the last line 
	 */
	bool needsSpace();

        // attributes
    private:
	/** Number of the current line in the output file */
	unsigned int m_nOutputLines;

	std::string m_source, m_srcPath;

	int m_verbose;

        /** number or errors detected */
        int m_nErrors;

        /** number of warning detected */
        int m_nWarnings;

        /** number of bad boxes detected */
        int m_nBadBoxes;

	/** Length of the previous line, to check if we need a space in the next line */
	size_t m_nLastLineLength;

	/**
	The line currently being parsed, with its leading whitespace intact.

	parseLine() is handed a trimmed line, because every detector matches
	from the first non-blank character. TeX's error context, though, encodes
	the column it stopped at as the indent of the continuation line -- it
	pads that line out to the exact width of the line above. Trimming
	destroys the only copy of that information, so keep the original here.
	*/
	std::string m_rawLine;

	bool m_nobadboxes;
	bool m_quiet;

        /**
        Stack containing the files parsed by the compiler. The top-most
        element is the currently parsed file.
        */
        std::stack<LOFStackItem> m_stackFile;

        /** The item currently parsed. */
        LatexOutputInfo m_currentItem;

	/** The last completed item, held back so that context can still reach it. */
	LatexOutputInfo m_pendingItem;
	bool m_hasPending;

	/** Whether the held-back item passed the -q/-b filter and will be printed. */
	bool m_pendingVisible;

	/** First half of a context block, waiting for the padded line below it. */
	TexContext m_ctxHead;
	size_t m_ctxHeadWidth;
	bool m_hasCtxHead;

	bool m_debugModel;

};
#endif
